eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/ 

spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: product-service

component:
  fakestore:
    name: fakestoreapi
    url: https://fakestoreapi.com

server:
  error:
    include-message: always